<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Auth\Events\Verified;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class EmailVerificationController extends Controller
{
    /**
     * Verify an email address from a signed, time-limited link.
     *
     * The link does not require an authenticated session: the HMAC signature
     * proves the link was generated by LonePay, and the hash binds it to the
     * exact email address, so it is safe to open on any device.
     */
    public function verify(Request $request, string $id, string $hash): JsonResponse|RedirectResponse
    {
        $user = User::find($id);

        if (! $user || ! hash_equals(sha1($user->getEmailForVerification()), $hash)) {
            abort(403, __('This verification link is invalid.'));
        }

        if (! $user->hasVerifiedEmail()) {
            $user->markEmailAsVerified();

            event(new Verified($user));
        }

        if ($request->wantsJson()) {
            return response()->json(['message' => __('Email address verified.')]);
        }

        return redirect()->away(
            rtrim((string) config('app.frontend_url'), '/').'/verify-email?verified=1'
        );
    }

    /**
     * Re-send the verification email to the authenticated user.
     */
    public function send(Request $request): JsonResponse
    {
        $user = $request->user();

        if ($user->hasVerifiedEmail()) {
            return response()->json(['message' => __('Email address is already verified.')]);
        }

        $user->sendEmailVerificationNotification();

        return response()->json(['message' => __('A fresh verification link has been sent.')]);
    }
}
